version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_VERSION=local
      - DB_HOST=mysql-local
      - SHOW_ENV=true
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"
